version: '3.9'
services:
  s3:
    image: quay.io/minio/minio
    volumes:
      - "./docker/minio:/data/:rw"
    restart: "on-failure"
    command: server --console-address ":9001" /data
    ports:
     - 9000:9000
     - 9001:9001
#   credentials are 'minioadmin:minioadmin'     
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
#      interval: 30s
#      timeout: 20s
#      retries: 3

  sqlite3:
    build:
      context: ./docker
      dockerfile: Dockerfile.sqlite
    volumes:
      - ./docker/sqlite/:/root/db/
    restart: "on-failure"

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./docker/reverse-proxy.conf:/etc/nginx/nginx.conf
    ports:
     - ${SERVE_PORT:-8088}:80
    depends_on:
      - s3
