version: '3.9'
services:
  s3:
    image: quay.io/minio/minio
    volumes:
      - "./docker/minio:/data/:rw"
    restart: "on-failure"
    command: server --console-address ":9001" /data
    ports:
     - 9000:9000
     - 9001:9001
#   credentials are 'minioadmin:minioadmin'     

  ui-initialize:
    image: node:18.12.1-alpine3.16  # this is lts-alpine3.16
    working_dir: /app
    volumes:
      - "./ui:/app/:rw"
    restart: "no"
    command: npm install && chmod -R 777 node_modules && npm run check && chmod -R 777 .svelte-kit

  ui:
    image: node:18.12.1-alpine3.16  # this is lts-alpine3.16
    working_dir: /app
    volumes:
      - "./ui:/app/:rw"
    ports:
      - 3000:3000
      - 24678:24678
      - 5173:5173
    restart: "on-failure"
    command: npm run dev

  sqlite3:
    build:
      context: ./docker
      dockerfile: Dockerfile.sqlite
    volumes:
      - ./docker/sqlite/:/root/db/
    restart: "on-failure"

  registry:
    image: registry:2.8
    ports:
      - 5000:5000
    volumes:
     - ./docker/registry/config.yaml:/etc/docker/registry/config.yml
    restart: "on-failure"
    depends_on:
      - s3

  registry-ui:
    image: joxit/docker-registry-ui:2.3.3
    ports:
      - 5500:80
    environment:
      - REGISTRY_TITLE=Arti Registry UI
      - REGISTRY_URL=http://localhost:5000
      - SINGLE_REGISTRY=true

  proxy:
    image: nginx:stable-alpine
    volumes:
      - ./docker/reverse-proxy.conf:/etc/nginx/nginx.conf
    ports:
     - ${SERVE_PORT:-8088}:80
    depends_on:
      - s3
